#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Oct 02 00:10:22 CST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab2_1_t_behav -key {Behavioral:sim_1:Functional:lab2_1_t} -tclbatch lab2_1_t.tcl -log simulate.log"
xsim lab2_1_t_behav -key {Behavioral:sim_1:Functional:lab2_1_t} -tclbatch lab2_1_t.tcl -log simulate.log

